eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/sapient/eureka/
  instance:
     preferIpAddress: true
server:
  port: 8081
spring:
  application:
    name: bookymymovie-zuul-service
zuul:
   routes:
    user-service:
        path: /user-service/**
        serviceId: user-service
        stripPrefix: true
    movie-service:
        path: /movie-service/**
        serviceId: movie-service
        stripPrefix: true
    booking-service:
        path: /booking-service/**
        serviceId: booking-service
        stripPrefix: true
    payment-service:
        path: /payment-service/**
        serviceId: payment-service
        stripPrefix: true