server:
  port: 8002
  servlet:
    context-path: /sapient
spring:
# datasource:
#    url: jdbc:mysql://localhost:3306/userDB?createDatabaseIfNotExist=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
 application:
    name: user-service
 devtools:
    restart:
      enabled: true
# jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

#Eureka Client Specific
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/sapient/eureka/
  instance:
     preferIpAddress: true

#Feign related
feign:
    hystrix:
        enabled: true

#Logging related
logging:
  level:
    org:
      hibernate:
        type: trace
    com:
      sapient:
        userservice:
          feignserviceclient: DEBUG
#Spring Security & oAuth related
#security:
#  oauth2:
#    client:
#      clientId: sapient
#      clientSecret: sapient123
#      accessTokenUri: http://localhost:9000/oauth2/token
#      userAuthorizationUri: http://localhost:9000/oauth2/auth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: http://localhost:9000/oauth2/user